Adiciona Base
BeatrizUser/site1-portfolio pull request #1
Opened 2022-02-17 19:46 UTC by BeatrizUser

Base  do projeto

2022-02-21 20:31 UTC, pedroorez commented on src/components/Corpo.js
> +      <Rodape/>
Esse rodapé ficaria melhor no APP.js eu acho

2022-03-09 16:15 UTC, pedroorez requested changes

2022-03-09 16:15 UTC, pedroorez commented on package.json
> +    "mdbreact": "^5.2.0",
Voce esta usando essa lib? Não achei referencias no codigo.

2022-03-09 16:15 UTC, pedroorez commented on src/App.test.js
>  import { render, screen } from '@testing-library/react';
Por enquanto pode apagar esse arquivo de testes. Vamos deixar isso mais pra depois.

2022-03-18 20:00 UTC, pedroorez approved these changes

2022-03-18 20:00 UTC, merged

2022-03-19 04:54 UTC, BeatrizUser commented
ok, vou ajeitar


Em seg., 21 de fev. de 2022 às 17:32, Pedro Correa ***@***.***>
escreveu:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/components/Corpo.js
> <https://github.com/BeatrizUser/site1-portfolio/pull/1#discussion_r811413687>
> :
>
> > +            </Card>
>
> +          </Col>
>
> +          <Col xs={6}>
>
> +            <Card>
>
> +              <Card.Body>
>
> +                <Card.Title>Novidades</Card.Title>
>
> +                <Card.Text>
>
> +                  Some quick example text to build on the card title and make up the bulk of
>
> +                  the card's content.
>
> +                </Card.Text>
>
> +              </Card.Body>
>
> +            </Card>
>
> +          </Col>
>
> +        </Row>
>
> +      </Container>
>
> +      <Rodape/>
>
>
> Esse rodapé ficaria melhor no APP.js eu acho
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BeatrizUser/site1-portfolio/pull/1#pullrequestreview-889081544>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC3TMKAEBF6TH2CLTTA5AOTU4KOMPANCNFSM5OVVVZIQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>